import Head from 'next/head'
import { makeStyles } from '@material-ui/core/styles';
import { 
    Avatar,
    Button, 
    Drawer, 
    Container,
    Modal,
    Card,
    CardContent
} from '@material-ui/core';
import { useState } from 'react';
import DrawerLeft from './drawer-left';
import TabOptions from './tabs';
import Dishes from './dishes';
import ModalDish from './modal-dish';

const drawerWidth = 100
const orderWidth = 300

const useStyles = makeStyles((theme) => ({
  root: {
    background: '#252836',
    border: 0,
    color: 'white',
    minHeight: '100vh',
    height: '100%',
    padding: '0 30px 30px',
    boxShadow: '0 3px 5px 2px rgba(255, 105, 135, .3)'
  },
  label: {
    textTransform: 'capitalize',
  },
  orderDrawer: {
    background: '#1F1D2B',
    width: orderWidth,
    alignItems: 'center'
  },
  appBar: {
    width: `calc(100% - ${drawerWidth+orderWidth}px)`,
    marginLeft: drawerWidth
  },
  paddingTB20: {
    paddingTop: 20,
    paddingBottom: 20
  },
  headerTitle: {
    display: 'flex',
    flexDirection: 'column'
  },
  title: {
    fontWeight: 'bold',
    fontSize: 20
  }
}))

export default function Home() {
  const classes = useStyles();
  const [openModal, setOpenModal] = useState(false)
  const [selectedItem, setSelectedItem] = useState({})
  const lista = [{
    id: 1,
    image: '/images/image4.png',
    description: 'Spicy seasoned seafood noodles',
    price: '$5',
    available: 10
  },
  {
    id: 2,
    image: '/images/image4.png',
    description: 'Spicy seasoned seafood noodles',
    price: '$5',
    available: 10
  },
  {
    id: 3,
    image: '/images/image4.png',
    description: 'Spicy seasoned seafood noodles',
    price: '$5',
    available: 10
  },
  {
    id: 4,
    image: '/images/image4.png',
    description: 'Spicy seasoned seafood noodles',
    price: '$5',
    available: 10
  }]

  const handleOpen = (dishIndex) => {
    setSelectedItem(lista[dishIndex])
    setOpenModal(true);
  };

  const handleClose = () => {
    setOpenModal(false);
  };

  return (
    <div className={classes.scrollHide}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="xl" classes={{root: classes.root}} className={classes.appBar}>
          <DrawerLeft/>

          {/* Meio */}
          
          <header className={`${classes.headerTitle} ${classes.paddingTB20}`}>
            <label className={classes.title}>
              Restaurante
            </label>
            <label className={classes.subTitle}>
              {new Date().toDateString()}
            </label>
          </header>

          <TabOptions/>

          <Dishes lista={lista} onClick={handleOpen}/>

          <Drawer 
          anchor={"right"} 
          variant="permanent"
          open 
          classes={{
            paper: classes.orderDrawer
          }}>
          </Drawer>
      </Container>

      <ModalDish 
        selectedItem={selectedItem}
        handleOpen={handleOpen}
        handleClose={handleClose}
        openModal={openModal}/>
    </div>
  )
}